name: Test

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  # Run Exhibition tests via xcodeproj
  test:
  
    runs-on: macos-13
    
    strategy:
      matrix:
        include:
        
        # Latest iOS
        - sdk: "iphonesimulator"
          destination: "platform=iOS Simulator,OS=16.2,name=iPhone 14 Pro Max"
          
        # Latest watchOS
        - sdk: "watchsimulator"
          destination: "platform=watchOS Simulator,OS=9.1,name=Apple Watch Series 8 - 45mm"
        
        # Latest macOS
        - sdk: "macosx13.1"
          destination: "platform=macOS"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Select Xcode
        uses: devbotsxyz/xcode-select@v1.1.0
        with:
          version: "14.2"
    
      - name: Build and Test
        run: |
          xcodebuild test \
            -project "Example.xcodeproj" \
            -scheme "Exhibition" \
            -sdk "${{ matrix.sdk }}" \
            -destination "${{ matrix.destination }}"

  # Build Example app to test sourcery generation & validate Package.swift
  example:
    
    runs-on: macos-13
    
    strategy:
      matrix:
        include:
          
        # Latest iOS Build
        - sdk: "iphonesimulator"
          scheme: "Example (iOS)"
          destination: "platform=iOS Simulator,OS=16.2,name=iPhone 14 Pro Max"
        
        # Latest macOS
        - sdk: "macosx13.1"
          scheme: "Example (macOS)"
          destination: "platform=macOS"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Select Xcode
        uses: devbotsxyz/xcode-select@v1.1.0
        with:
          version: "14.2"
      
      - name: Install sourcery
        run: brew install sourcery
      
      - name: Build and Test
        run: |
          xcodebuild build \
            -project "Example.xcodeproj" \
            -scheme "${{ matrix.scheme }}" \
            -sdk "${{ matrix.sdk }}" \
            -destination "${{ matrix.destination }}"
